### ISSUE TITLE
DataCITE mapping feedback

### ISSUE THREAD

**Issue by louatbodc** [rdawg-pidinst/schema#25]
Hi Rolf

Thanks for doing this. It certainly highlights some issues as you have pointed out. As you say, some of the DataCite properties do seem a bit tenuous for describing instruments and seem to need a lot of explanation for an end-user to apply appropriately. While I understand the DataCite schema is meant to be flexible (to allow it to be used across domains and applications), is there a risk this could also lead to different variations of instrument instance schemas, reducing interoperability and discoverability? 

I can see there are instruments already in DataCite using some of these properties with resourceGeneralType = 'Physical object' so it is possible to use the DataCite properties. Though based on the XML, I do sometimes struggle to know if I'm looking at an instrument instance or an identifier for an instrument type/model in an inventory[1,2]. This is why it would be good to have a more specific resourceGeneralType and to include some of the more specific instrument properties (e.g. ModelNumber, SerialNumber, dates, owner etc.)

Cheers
Lou

[1] https://search.datacite.org/works/10.7282/t3pr7z04
[2] https://search.datacite.org/works/10.7282/t3nv9mcd

**Comment by markusstocker** [comment]
Hi Rolf, thanks, indeed. I reviewed the material and I agree with your observations. I also think that Lou is right that schema flexibility comes at the cost of interoperability.

**Comment by RKrahl** [comment]
Hi @louatbodc: concerning the interoperability issue: that is exactly why I suggest that we would need extended documentation on instrument PIDs in the DataCite schema with clear guidelines.  I do hope that such guidelines could streamline the creation of the metadata to an extend that interoperability will be provided in practice.

**Comment by RKrahl** [comment]
I guess this has been settled by now. I suggest to close.

**Comment by RKrahl** [comment]
Close as discussed in to meeting today.
