### ISSUE TITLE
Publisher as publisher of DOI

### ISSUE THREAD

**Issue by tedhabermann** [rdawg-pidinst/schema#26]
Text: Publisher does not seem to fit at all for instruments. But it is mandatory in the DataCite schema, so we can not skip it. Need to negotiate with DataCite what to put here. Maybe the institution responsible to manage this DOI record and its metadata?

I like this idea

**Comment by RKrahl** [comment]
I guess there is no action that need to be taken from this. I suggest to close.

**Comment by RKrahl** [comment]
Close as discussed in to meeting today.
