### ISSUE TITLE
Handbook

### ISSUE THREAD

**Issue by tedhabermann** [rdawg-pidinst/schema#29]
some sort of a dedicated handbook on how to correctly create instrument metadata using this schema will be needed.

Definitely! Good examples are also important. Perhaps even an interface with integrated guidance.

We may also want to include guidance about practices that are discouraged,

**Comment by RKrahl** [comment]
In the meanwhile we have the  [white paper](https://rda-pidinst.readthedocs.io/en/latest/white-paper/) that is supposed to serve that purpose. If there are any suggestions for improvements, these should be discussed [there](https://github.com/rdawg-pidinst/white-paper). I suggest to close this issue.

**Comment by RKrahl** [comment]
Close as discussed in to meeting today.
