### ISSUE TITLE
resourceTypeGeneral

### ISSUE THREAD

**Issue by tedhabermann** [rdawg-pidinst/schema#30]
It would be desirable to add "Instrument" to the controlled list of values for resourceTypeGeneral.

We suggested platform, instrument, or sensor for resourceType. If we add instrument to resourceType do we use it for all three? Maybe "device" would accomplish the goal but also be general?

**Comment by RKrahl** [comment]
I would say, yes, `resourceTypeGeneral=Instrument` would fit for all three `resourceType` values. I'd consider "device" to be to unspecific.

**Comment by markusstocker** [comment]
Talking about being specific, IMO we need to clarify whether we should speak of "MeasuringInstrument". There may be a time when clarinets are identified by DOI.

**Comment by RKrahl** [comment]
"MeasuringInstrument" sounds too complicated for my guts feeling.

Also I don't think there is a need to exclude other, not-measuring instruments here. I agree to limit the scope of the group to measuring instruments, e.g. we will only consider those when we define the PID infrastructure and formulate the metadata schema. But if later on somebody come along and find the result to be useful for other types of instruments as well, why not, it does not harm if the result  is used for other purposes as well.

**Comment by RKrahl** [comment]
This is now discussed in datacite/datacite#1670. I suggest to close here.

**Comment by RKrahl** [comment]
Close as discussed in to meeting today.
