### ISSUE TITLE
Metadata Schema - Elements

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [rdawg-pidinst/schema#32]
1. Identifier
-- 'Unique string that ..' - does it to be only string?
-- 'Allowed values, constraints, remarks' - what is 'PIDINST'? in the context of this metadata element?

2. Description - this refers to technical specification of a device, which can be a url too (besides free-text). i dont think it is feasible to submit all tech details of an instrument to the PID service. so we may consider including an attribute to this element.

3. Controlled list of values - datacite metadata schema's controlled list values are a list of enumeration. we cannot find their meaningful information on the web unless we refer to the scheme documentation. in future i suggest we consider using vocabularies identified with uri.

4. the time related to an instrument can be specified through the schema, its location is missing. note that the location can be spatial or toponym. is there a specific reason why we decided to exclude location information from the schema?

**Comment by RKrahl** [comment]
Some comments:

- Ad 1. Identifier:
  An identifier is an opaque bit of information that has no semantic meaning at all by itself other then uniquely identifying the entity it represents. It is commonly stored as a string, What else do you have in mind?
  The name `PIDINST` is used in the schema merely as a placeholder for the type of instrument PID while there is no final decision on the technical platform to be used. If we go for DataCite DOIs, it stands for `DOI`, if we go for ePIC, it stands for `Handle`.

- Ad 2. Description:
  You ask for another attribute to link external technical specification? We already have that in the schema: `RelatedIdentifier` with `relationType=IsDescribedBy`.

- Ad 3. Controlled list of values:
  I'm not sure if I completely understand your suggestion, you mean we should use some type registry for the attributes having controlled lists of values and reference them by the type PID issued by the registry? Sure, we could do that and this approach certainly has its merits. But it would require a significant amount of extra work and I don't believe we have the resources to do that in this working group.

- Ad 4. location:
  This has already been discussed in #17. The conclusion was that there are many unresolved issues with that. It has been suggested to rather link deployments of an instrument externally using `RelatedIdentifier` (needs the definition of a suitable `relationType`, though).

**Comment by kitchenprinzessin3880** [comment]
Hi Rolf,
1. Identifer - 'string' - i want to confirm if it only allows [a-zA-Z] or alphanumerics (\w)
2. RelatedIdentifier with relationType=IsDescribedBy --> noted. 
3. significant amount of extra work --> please provide definition of the enumerations. 
4. location -> noted.

**Comment by RKrahl** [comment]
I submitted #44 that hopefully clarifies the value for `identifierType`. Otherwise I assume that this issue has been settled by now. I suggest to close.

**Comment by RKrahl** [comment]
Close as discussed in to meeting today.
