### ISSUE TITLE
Add controlled value 'IsIdenticalTo' to relationType attribute

### ISSUE THREAD

**Issue by louatbodc** [rdawg-pidinst/schema#37]
Enables the identification of duplicate instruments registered under a different PID identifier. This is similar to the usage by DataCite

**Comment by RKrahl** [comment]
There is already #23 considering the allowed values for `relationType`. I suggest to move the discussion over there in order to have it all at one place and close this one as a duplicate.

**Comment by RKrahl** [comment]
Close as discussed in to meeting today.
