### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by RKrahl** [rdawg-pidinst/schema#41]
I guess we are at a stage where we should start to use consistent version numbers for the schema. As a result of the latest changes to the schema (e.g. #40) we now have instruments PIDs in the wild using slightly different and incompatible variants of the schema, before and after that change respectively.

**Comment by hauschke** [comment]
+1. Development of tools etc. would be much easier when releases would be used, too.

**Comment by RKrahl** [comment]
We may also consider adding a `version` property to the schema.
