### ISSUE TITLE
Schema File

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [rdawg-pidinst/schema#46]
@RKrahl @markusstocker 
Where can I find the XML schema of https://github.com/rdawg-pidinst/schema/blob/master/schema.rst?

**Comment by RKrahl** [comment]
We don't have any, I'm afraid.  The schema is formulation is technology agnostic, representation of the metadata as XML would only be one of the possible options.

**Comment by RKrahl** [comment]
I guess we could add a XML Schema Definition file just for the sake of documentation. But I suggest that we wait for version 1.0 to be finalized and then only update that on each version release.
